language: python
env:
  global:
  - secure: "Zg763XUTfvxQjv+GjwmoF42tsZ3P+jgO0qWrJJc8qB6GLQR9BjN6phqt9mRzpwmwhmEbninPRacStjT8iHQP/EPhc3nSRIuxwLaemFgW6tIkAidSxKuf8PrggMIDbBdl2klXt3G6fB2T8SNQ/0YeXPYESr5BiZJ4c54hVT08sHE=" # AWS_ACCESS_KEY_ID
  - secure: "onU/+E7Hs3c738NQ9ViI6Yuj4DikukloXq9xc9qm+5ZVeULrtStT7EGURzjdZ+X8Tv3OMyhfNF8kciUDBZnaV//JtKX04dCwadNyEF2yKsrpIcIArKTdS+c+zIsnSmZrrpQfc2vKWLmAQDqLKk7KgQblVI9mIZg+25ZeQUOQmLY=" # AWS_SECRET_ACCESS_KEY
  - AWS_DEFAULT_REGION=eu-west-1
python:
- '3.6'
install:
- pip install yamllint
- pip install cfn-lint
- pip install awscli
script:
- yamllint .
- cfn-lint alerta.yaml
- aws cloudformation validate-template --template-body file://alerta.yaml
- aws cloudformation validate-template --template-url https://s3-eu-west-1.amazonaws.com/alerta/public/cloudformation/alerta.yaml
